name: Pipeline [test -> build -> deploy]
on:
  push:
    branches:
      - '**'

permissions:
  contents: read
  packages: write

concurrency:
  # Only cancel in progress when on a branch - use SHA on main to ensure uniqueness.
  # This will allow multiple pipelines to run at the same time on main.
  # Note that two pipelines running within a few minutes of each other will cause issues with helm deploying to
  # a namespace, as the second one will not be able to get a lock as a deploy will be in progress.
  group: ${{ github.workflow }}-${{ github.ref == 'refs/heads/main' && github.sha || github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  app_version:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.app_version.outputs.version }}
    steps:
      - id: app_version
        name: Application version creators
        uses: ministryofjustice/hmpps-github-actions/.github/actions/build-test-and-deploy/create_app_version@v2 # WORKFLOW_VERSION
  gradle_verify:
    name: Run the tests
    uses: ministryofjustice/hmpps-github-actions/.github/workflows/gradle_verify.yml@v2 # WORKFLOW_VERSION
    secrets: inherit
    with:
      gradle-command: 'BUILD_NUMBER=${{ needs.app_version.outputs.version}} ./gradlew assemble check'
      upload-build-artifacts: ${{ github.ref == 'refs/heads/main' }}
      java-version: "25"
    needs:
      - app_version
  publish:
    name: Publish the artifact
    if: github.ref == 'refs/heads/main'
    uses: ./.github/workflows/publish.yml # LOCAL_VERSION
    secrets: inherit
    needs:
      - gradle_verify
